#!/bin/bash
#packages needed
sudo apt-get update
sudo apt-get install git-core gnupg flex bison gperf build-essential zip curl libc6-dev libncurses5-dev:i386 x11proto-core-dev libx11-dev:i386 libreadline6-dev:i386 libgl1-mesa-glx:i386 libgl1-mesa-dev g++-multilib mingw32 openjdk-6-jdk tofrodos python-markdown libxml2-utils xsltproc zlib1g-dev:i386 gcc

#toolchain
echo -n "where is your toolchain located? (If you followed the tutorial put '~/toolchains/android_prebuilt/linux-x86/toolchain/arm-eabi-4.4.3/bin/arm-eabi-'): "
read toolchain

#source
echo -n "Do you need to download source? (y/n): "
read dl
if $dl = y
then
echo -n "where is the source? Give a github link: "
read source
mkdir ~/kernel
cd ~/kernel
git clone $source
else
echo "Where is the source on your hard drive: "
read location
cd $location
fi

#config
echo -n "Whats your device name? (Cdma One V is primoc): "
read config
make $config_defconfig

#now to open menuconfig
echo "you can now edit your config"
sleep 5
make menuconfig

#build
make -j`grep -c processor /proc/cpuinfo` ARCH=arm CROSS_COMPILE=$toolchain
echo "your kernel and modules are ready check the last few lines for their location"